spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: serviceBooks
        uri: lb://service-Books
        predicates:
        - Path=/books/**
        filters:
        - RewritePath=/books/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-books
            fallbackUri: forward:/fallback/serviceBooks
      - id: serviceA
        uri: lb://service-A
        predicates:
        - Path=/srva/**
        filters:
        - RewritePath=/srva/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-srvA
            fallbackUri: forward:/fallback/serviceA
      - id: ServiceB
        uri: lb://service-B
        predicates:
        - Path=/srvb/**
        filters:
        - RewritePath=/srvb/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-srvB
            fallbackUri: forward:/fallback/serviceB  
      - id: ServiceWeather
        uri: lb://service-Weather
        predicates:
        - Path=/weather/**
        filters:
        - RewritePath=/weather/(?<segment>.*), /$\{segment}
        - name: Hystrix
          args:
            name: monitor-weather
            fallbackUri: forward:/fallback/serviceWeather  
      - id: MQActivityService
        uri: lb://activity
        predicates:
        - Path=/act/**
        filters:
        - RewritePath=/act/(?<segment>.*), /$\{segment} 
    consul:
      discovery:
        instanceId: Gateway
        health-check-interval: 5s
      config:
        management: 
          enabled: true
management:
  security: 
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health
hystrix:
   dashboard:
       proxy-stream-allow-list: "*"
